const tap = require('tap');
const tekstable = require('../main');

tap.test('simple default value table', (childTest) => {
    const table = [
        ['No', 'Name', 'UUID', 'Scope', 'Enabled'],
        ['1', 'UNHumanRight_H_Comissio', 'd49ba7c7-016a-1000-0000-00005519f6d2', 'Global', 'false'],
        ['2', 'LKK_AvroRecordSetWriter', 'c33bt9c1-923g-2310-1010-10105282g3s1', 'Global', 'true']
    ];

    const tableString = tekstable(table, { spacing: 2, isHeader: true});

    const assertString = `+------+---------------------------+----------------------------------------+----------+-----------+
|  No  |  Name                     |  UUID                                  |  Scope   |  Enabled  |
+------+---------------------------+----------------------------------------+----------+-----------+
|  1   |  UNHumanRight_H_Comissio  |  d49ba7c7-016a-1000-0000-00005519f6d2  |  Global  |  false    |
|  2   |  LKK_AvroRecordSetWriter  |  c33bt9c1-923g-2310-1010-10105282g3s1  |  Global  |  true     |
+------+---------------------------+----------------------------------------+----------+-----------+`;

    // Assert equal for table string generated by module and actual table
    childTest.equal(tableString, assertString, 'Tables are same');
    
    childTest.end();
});